name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: |
          rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true
          rm -f $GITHUB_WORKSPACE/builds/*.jar || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Access Secrets
        env:
          # semua secrets Anda tetap di sini...
          TMDB_API: ${{ secrets.TMDB_API }}
          DUMP_API: ${{ secrets.DUMP_API }}
          # ... (secrets lainnya)
          KAISVA: ${{ secrets.KAISVA }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo "Menulis secrets ke local.properties..."
          {
            echo TMDB_API=$TMDB_API
            echo DUMP_API=$DUMP_API
            # tambahkan semua secrets lainnya seperti sebelumnya
            echo KAISVA=$KAISVA
          } >> local.properties

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew

          echo "▶️ Menjalankan Gradle build..."
          ./gradlew make makePluginsJson || { echo "❌ Gradle 'make' gagal"; exit 1; }

          ./gradlew ensureJarCompatibility || { echo "❌ Gradle 'ensureJarCompatibility' gagal"; exit 1; }

          echo "📁 Menampilkan file .jar dan .cs3:"
          find . -name "*.jar" -o -name "*.cs3" || true

          echo "🔍 Mengaktifkan globstar..."
          shopt -s globstar nullglob

          echo "📦 Menyalin .cs3 dan .jar ke folder builds..."
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || echo "⚠️ Tidak ada file .cs3 ditemukan"
          cp **/build/*.jar $GITHUB_WORKSPACE/builds || echo "⚠️ Tidak ada file .jar ditemukan"

          if [ -f build/plugins.json ]; then
            cp build/plugins.json $GITHUB_WORKSPACE/builds
          else
            echo "⚠️ plugins.json tidak ditemukan"
          fi

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || echo "ℹ️ Tidak ada perubahan untuk commit"
          git push --force
          