# This tool was written by @keyiflerolsun for @KekikAkademi.
name: CloudStream Compiler

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamCompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 'src' Repository
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Check out 'build' Repository
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean Old Builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Set up JDK 23
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 23

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson --stacktrace --info
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Upload Builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build of $GITHUB_SHA" || exit 0   # if there's nothing to commit, don't error
          git push --force
          